### ISSUE TITLE
Design consistent user friendly error output

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/abrute#1]
Errors have inconsistent behavior.  Create a nice experience.

Structure the main application so all errors will produce a relevant error description to an end user.  No errors are to be displayed relating to code in a released binary.  Errors should be pleasant to read… as in easy on the eyes and easy to understand.

**Comment by danielpclark** [comment]
# Current Errors

### 1) Invalid Range

Input:
```bash
abrute asdf asdf -- asdf
```

Output:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', /checkout/src/libcore/result.rs:906:4
```

### 2) File Missing

Input:
```bash
abrute 4 asdf -- asdf
```

Output:
```
Error: File "asdf" does not exist.
error: "Please verify last argument is the proper filename."
```
### 3) Missing Double Dash

Input:
```bash
abrute 4 asdf asdf
```

Output:
```
error: Found argument 'asdf' which wasn't expected, or isn't valid in this context

USAGE:
    abrute [OPTIONS] <RANGE> <CHARACTERS> [--] <TARGET>

For more information try --help
```
_Note the options are in the wrong location and the dash dash should not be boxed in this message._

### 4) Invalid Adjacent Number

Input:
```bash
abrute 4 asdf -a g -- asdf
```

Output:
```
error: Invalid value for '--adjacent <adjacent>': The value did not contain valid digit from 0 to 255
```

### 5) Invalid Character Start Sequence

_Using characters that don't exist in the sequence for the start._

Input:
```bash
abrute 4 asdf -s 1234 -- asdf
```

Output:
```
thread 'main' panicked at 'no entry found for key', /checkout/src/libcore/option.rs:839:4
```
